name: OnlyPuppies Bluesky Workflow

on:
  schedule:
    - cron: "20 04 * * *" # Runs twice a day, at 1:00 PM and 10:00 PM UTC

  workflow_dispatch:
    # Allows manual triggers of the workflow for testing.

jobs:
  post_puppy_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests openai pillow image

      - name: Run OnlyPuppies Bot
        env:
          BLUESKY_PUPPIES_H: ${{ secrets.BLUESKY_PUPPIES_H }}
          BLUESKY_PUPPIES_P: ${{ secrets.BLUESKY_PUPPIES_P }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python src/onlypuppies_bot.py
